### ISSUE TITLE
[Bug] Stops working when "light theme" is manually clicked in gnome system settings

### ISSUE THREAD

**Issue by hellerbarde** [fthx/theme-switcher#1]
If the "light" setting is chosen in gnome settings, org.gnome.desktop.interface.color-scheme is set to "default" and not "prefer-light".

I am not sure what the semantics of "default" are. But it currently falls through to the "theme switching error" error message in this extension. 

It would be awesome if you could fix this, but it's a small bother, so no rush.

If anyone comes here from google: Go to System Settings -> Appearance  and click "Style: Dark", and from there on, this extension will work again.

**Comment by fthx** [comment]
Ok I will do that.
Ubuntu prefs (v41 patched) do switch between prefer-light/dark, not default, so I did miss this...
