### ISSUE TITLE
Different Panel Icon

### ISSUE THREAD

**Issue by mlmilliman** [fthx/theme-switcher#3]
I know that this is a little nit but could you please change the icons for the light and dark themes? They conflict with the weather extension I'm using in the panel. I cannot figure out which icon to click.
![Screenshot from 2022-04-30 14-41-01](https://user-images.githubusercontent.com/11722868/166121990-d4fe48f7-3571-4336-95ec-f6759abfd164.png)

**Comment by fthx** [comment]
No sorry, I understand your problem but I've never succeeded to satisfy everybody with theme icons.
The only solution would be to propose a choice of icons in UI but I won't do that in such a simple extension.
