### ISSUE TITLE
Option to move it to the system menu

### ISSUE THREAD

**Issue by Feichtmeier** [fthx/theme-switcher#4]
Hi @fthx :wave: 
Yet again super useful extension :)

Sometimes if I am really "fat-fingered" I accidently click the theme switcher in the panel. Could you eventually  move the button to the system menu as a switch? 
For example as an option? Wouldn't need to be the default option, even if I think this would be cooler
![image](https://user-images.githubusercontent.com/15329494/166140823-1534ffb1-8c5e-40f9-a4b2-31cd85a59cd1.png)

Best regards

**Comment by fthx** [comment]
Hi!

Sorry I won't have the time to do that, but for sure you can find that more convenient.
Maybe that could become another extension but I won't do this one!
:-p

**Comment by Feichtmeier** [comment]
It's np it's in gnome shell now

**Comment by fthx** [comment]
Aaaah that's true, I did not see this part in GS 43 menu.
I'm not that up to date, I do use Jammy + snaps. (Yes, your snap too.) (And firmware one since it is now connected to fwupd.)
