### ISSUE TITLE
Not loading extension icon

### ISSUE THREAD

**Issue by rodrigofructuoso** [fthx/theme-switcher#5]
Hi, @fthx,

Thanks for the extension, simple and useful.

I'm using it on Pop! Os 22.04 which uses GNOME 42 and the only question there I'm facing is that the extension icon to toggle theme isn't loading. I suppose that could be some missing dependency. I've tried googling the names 'weather-clear-symbolic' and 'weather-clear-night-symbolic' but I wasn't successful finding a candidate for the problem solution.

![image](https://user-images.githubusercontent.com/5731898/171065727-f6222417-29d7-48a0-b86f-e2f2f1d35436.png)

Best regards!

**Comment by fthx** [comment]
Hi, do you have at least Adwaita icon set installed?
