### ISSUE TITLE
centos 8.5， can't enter desktop after installing.

### ISSUE THREAD

**Issue by zququ** [fthx/theme-switcher#6]
Hi
centos 8.5, can't enter desktop after installing this, PLEASE HELP！ How to uninstall it？

**Comment by fthx** [comment]
You have GS 42 ?

Just delete my extension folder in console.

**Comment by zququ** [comment]
gnome 3.32.2, actually theme-switcher has not been installed after I have checked the extension folder in the emergency mode. 

I have entered the desktop after restoring the gnome default configuration.

Thanks for replying！

**Comment by zququ** [comment]
> 

gnome 3.32.2, actually theme-switcher has not been installed after I have checked the extension folder in the emergency mode.

I have entered the desktop after restoring the gnome default configuration.

Thanks for replying！
